### ISSUE TITLE
Failed to open

### ISSUE THREAD

**Issue by MauroMardones** [pepijn-devries/CopernicusMarine#14]
Im trying to download this 

`copernicus_download_motu(
  username = CopernicusMarine_uid,
  password = CopernicusMarine_pwd,
  destination = dir1,
  product = "GLOBAL_MULTIYEAR_PHY_001_030" ,
  layer = "cmems_mod_glo_phy_my_0.083_P1M-m",
  variable = "Temperature",
  output = "netcdf",
  region = c(-85, -75, -30, -55), # (xmin,ymin,xmax,ymax)
  timerange = c("2005-01-01 12:00:00","2020-12-31 12:00:00"),
  sub_variables = c("thetao"),
  verticalrange = c(0, 50)
)`

but i get this:

`Already logged in
Preparing download...
Downloading file...
Failed to collect information from Copernicus.
Path exists and overwrite is FALSE`

im working on my own project, where, 
Data folder is
`dir1 <- here("Data")`

Do you know why?

**Comment by pepijn-devries** [comment]
Hi @MauroMardones,

The problem that you describe here seems to be a network issue, and not so much an issue with the package.

In addition, there are several issues with what you try to do:

 * `Temperature` is not a variable in your product, `thetao` is.
 * The subset you try to download is large. When testing, try to keep it to a minimum.
 * When reporting issues, please try to include a reprex (https://reprex.tidyverse.org/), and preferably a `backtrace()` in case of an error and some `sessionInfo()`

I've run the following code with success (not that I've stored my account details with `option`):

```r
library(CopernicusMarine)
copernicus_download_motu(
  destination = tempdir(),
  product = "GLOBAL_MULTIYEAR_PHY_001_030",
  layer = "cmems_mod_glo_phy_my_0.083_P1M-m",
  variable = "thetao",
  output = "netcdf",
  region = c(-85, -75, -30, -55),
  timerange = c("1993-01-16 12:00:00","1993-01-31 12:00:00"),
  verticalrange = c(0, 50))
```
If you can confirm that the code above works, I will close this issue

**Comment by MauroMardones** [comment]
yep. You are rigth. The issue is with the proxies. I dont know why, but and the solution was [here](https://stackoverflow.com/questions/27761799/error-installing-homebrew-on-mac-curl-6-could-not-resolve-host-raw-githubus) however, it was much simpler, just restore my laptop. 

Thanks for your help
