### ISSUE TITLE
options instead of option?

### ISSUE THREAD

**Issue by CongGao-CG** [pepijn-devries/CopernicusMarine#20]
> username Your Copernicus marine user name. Can be provided as option(CopernicusMarine_uid
= "my_user_name"), or as argument here.
password Your Copernicus marine password. Can be provided as option(CopernicusMarine_pwd
= "my_password"), or as argument here.

I tried `option(CopernicusMarine_pwd = "XXX")`. It returned
Error in option(CopernicusMarine_pwd = "XXX") : 
  could not find function "option"

And `options(CopernicusMarine_pwd = "XXX")` worked for me.

`version` gave
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.2                         
year           2022                        
month          10                          
day            31                          
svn rev        83211                       
language       R                           
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting

**Comment by pepijn-devries** [comment]
Hi @CongGao-CG,

Thanks for your feedback. You are right. These are typos in the documentation. I will fix those in the next release.

**Comment by pepijn-devries** [comment]
Fixed with commit https://github.com/pepijn-devries/CopernicusMarine/commit/9bfe79421c309b174f0ecd8e9e4377529f9ba6eb
