### ISSUE TITLE
Error to connect to server

### ISSUE THREAD

**Issue by teuzindahuz** [pepijn-devries/CopernicusMarine#27]
Sear Pepijn,

thank you for the package. 
I get a 

> Failed to collect information from subset-job. HTTP 400 Bad Request.

, trying to subset this dataset:

```
cms_download_subset(
  destination   = destination,
  product       = "BALTICSEA_REANALYSIS_WAV_003_015",
  layer         = "cmems_mod_bal_wav_my_2km-climatology_P1M-m", # Replace with the correct layer name
  variable      = "sea_surface_wave_significant_height",
  region        = c(10, 53, 11, 54), # Replace with the desired region coordinates
  timerange     = c("2021-05-15", "2021-05-25")# Replace with desired depth range if applicable
)
```

As I have successfully worked out your example, do you think that's a problem with the availability of the dataset? Or is it somwthing wrong with my request?

Thank you in advance for your help!

Best,
Matteo

**Comment by pepijn-devries** [comment]
Hi Matteo (@teuzindahuz),

Note that the layer you are requesting cannot be obtained with the subsetting request:
You can see if you call `cms_product_services("BALTICSEA_REANALYSIS_WAV_003_015")` or visit https://data.marine.copernicus.eu/product/BALTICSEA_REANALYSIS_WAV_003_015/services. You should be able to subset the layer 'dataset-bal-reanalysis-wav-hourly', however that does not seem to be working either. That is something that I will need to fix. For the time-being you can still use `copernicus_download_motu`, or you can download the full data with `cms_download_stac`. I will report my progress on fixing the issue here...

Cheers,

Pepijn

**Comment by pepijn-devries** [comment]
After some fixes in commit https://github.com/pepijn-devries/CopernicusMarine/commit/685d209408f175c62f732929ab0b7e406d304aa9

```
dest <- tempfile(fileext = ".nc")
cms_download_subset(
  destination   = dest,
  product       = "BALTICSEA_REANALYSIS_WAV_003_015",
  layer         = "dataset-bal-reanalysis-wav-hourly",
  variable      = c("VHM0","VHM0_SW1","VHM0_SW2","VHM0_WW","VMDR","VMDR_SW1","VMDR_SW2","VMDR_WW","VPED","VSDX","VSDY","VTM01_SW1","VTM01_SW2","VTM01_WW","VTM02","VTM10","VTPK"),
  region        = c(10, 53, 11, 54),
  timerange     = c("2021-05-15", "2021-05-15"),
  overwrite     = TRUE
)
```

Somehow, it only works when all variables are selected. This requires some additional tests to fix. To be continued....

**Comment by pepijn-devries** [comment]
Some more tweaks in commit https://github.com/pepijn-devries/CopernicusMarine/pull/29/commits/9d08d7b9ddff1e3269dff4fc9bc5eb076466efa9

**Comment by pepijn-devries** [comment]
Hi Matteo (@teuzindahuz),

After installing the latest github version:

```
devtools::install_github('pepijn-devries/CopernicusMarine')
```

The following code should work:
```
details <- cms_product_details("BALTICSEA_REANALYSIS_WAV_003_015", variant = "detailed-v2")
names(details$layers)
dest <- tempfile(fileext = ".nc")
cms_download_subset(
  destination   = dest,
  product       = "BALTICSEA_REANALYSIS_WAV_003_015",
  layer         = "dataset-bal-reanalysis-wav-hourly",
  variable      = "VHM0",
  region        = c(10, 53, 11, 54),
  timerange     = c("2021-05-15", "2021-05-15"),
  overwrite     = TRUE
)
```

**Comment by teuzindahuz** [comment]
Hi Pepijn,

thank you for the quick reply! Your package is really useful for R users!
Thank you for your great job!

Best,
Matteo
