### ISSUE TITLE
Variables name

### ISSUE THREAD

**Issue by DevrekerD** [pepijn-devries/CopernicusMarine#30]
Hello, thank you for your R tool, which is very useful for quickly finding and downloading COPERNICUS products without having to go through their protail every time!
However, the latest changes in the CMEMS Data Store prevent me from using your tool correctly, even after your latest update.
It seems that the variable names given in the product web page doesn't correspond to the variable names that should be entered in the cms_download_subset() function! 

Apart from the example you give in the R thumbnail, I haven't managed to extract any satellite data, for example :
  OCEANCOLOUR_ATL_BGC_L3_MY_009_113
  cmems_obs-oc_atl_bgc-plankton_my_l3-olci-300m_P1D
  CHL
no longer works.
Do you have any idea to fix this probem ?
Sincerely.

**Comment by pepijn-devries** [comment]
Hi @DevrekerD ,

with `cms_product_details` you can get a list of available layers and variables for a product. For me the following code works:

```
details <- cms_product_details("OCEANCOLOUR_ATL_BGC_L3_MY_009_113", variant = "detailed-v2")
names(details$layers)
dest <- tempfile(fileext = ".nc")
cms_download_subset(
  destination   = dest,
  product       = "OCEANCOLOUR_ATL_BGC_L3_MY_009_113",
  layer         = "cmems_obs-oc_atl_bgc-plankton_my_l3-olci-300m_P1D",
  variable      = "CHL",
  region        = c(2, 54, 3, 55),
  timerange     = c("2021-01-01", "2021-01-01"),
  overwrite     = TRUE
)
```

Please let me know if this fixes your issue, such that I can close it.

Cheers,

Pepijn

**Comment by DevrekerD** [comment]
Thanks to responding so quickly.
However, your example still doesn't work !! 
I have this R message :

Preparing job...
Failed to collect information from subset-job.
HTTP 400 Bad Request.

**Comment by pepijn-devries** [comment]
Hi @DevrekerD ,

Without a complete reprex and session info, it is difficult to help you. From the information you have provided, I suspect that you are experiencing the same issue as reported here:

https://github.com/pepijn-devries/CopernicusMarine/issues/27

Have you tried the solution offered there (installing the development version of the package)? `devtools::install_github('pepijn-devries/CopernicusMarine')`.

Please let me know if this fixes your problem.

Cheers,

Pepijn

**Comment by pepijn-devries** [comment]
Thanks for confirming. I will submit to CRAN in a bit.
