### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by linnetjessell** [pepijn-devries/CopernicusMarine#40]
I keep randomly getting this error code: "Request failed with status code 403" when trying to download subsets of data, but it doesn't happen every time. Some downloads work and others don't even though I am trying to download the same exact subset of data. I have tested to see if the cms_login in works and it does, even when the subset download doesn't. Can you please suggest a fix for this or explain why I might be receiving this error but only sometimes?

**Comment by pepijn-devries** [comment]
Hi @linnetjesell,

As this error does not seem to be reproducible with this package and the given status code indicates a server error, it seems that this is something I cannot fix within this package. This is something I will have to ask the people at CopernicusMarine. I will leave this issue open until I have a more helpful answer...

**Comment by pepijn-devries** [comment]
The http response is now 404. To keep the issues tidy, I will close this issue and refer to https://github.com/pepijn-devries/CopernicusMarine/issues/42
