### ISSUE TITLE
Issue with cms_download_subset

### ISSUE THREAD

**Issue by FMestre1** [pepijn-devries/CopernicusMarine#45]
Hello,
I ran the example code:

destination <- tempfile("copernicus", fileext = ".nc")

cms_download_subset(
  destination   = destination,
  product       = "GLOBAL_ANALYSISFORECAST_PHY_001_024",
  layer         = "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m",
  variable      = "sea_water_velocity",
  region        = c(-1, 50, 10, 55),
  timerange     = c("2021-01-01 UTC", "2021-01-02 UTC"),
  verticalrange = c(0, -2)
)

But I've got this error:

Failed to collect information from subset-job.
HTTP 404 Not Found.

Does this have something to do with migrating data to the Marine Data Store? How can I correct this?

Thanks,
Frederico

**Comment by pepijn-devries** [comment]
Thanks for reporting, but please check open issues, before opening new ones. See:

https://github.com/pepijn-devries/CopernicusMarine/issues/42

**Comment by FMestre1** [comment]
Ok, thanks.
